trigger: 'none'

jobs:
- job: WebApp
  displayName: 'Build Web App'
  pool:
    vmImage: 'windows-2019'
  variables:
    buildConfiguration: release

  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/WebApp.csproj'

  - powershell: |
     $paths = Get-ChildItem -include *.csproj -Recurse
     foreach($pathobject in $paths) 
     {
         $path = $pathobject.fullname
         $doc = New-Object System.Xml.XmlDocument
         $doc.Load($path)
         $child = $doc.CreateElement("ProjectGuid")
         $child.InnerText = [guid]::NewGuid().ToString().ToUpper()
         $node = $doc.SelectSingleNode("//Project/PropertyGroup")
         $node.AppendChild($child)
         $doc.Save($path)
     }
    workingDirectory: WebApp
    displayName: 'PS : Add Project GUID'
    enabled: false
  
  - task: SonarCloudPrepare@3
    displayName: 'Prepare Analysis on SonarCloud'
    inputs:
      SonarQube: 'svc-sonar'
      organization: 'azdvptreinamento'
      projectKey: 'WebAppwithDatabaseDemoKey'

  - task: DotNetCoreCLI@2
    displayName: Build Web App
    inputs:
      command: 'build'
      projects: '**/WebApp.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: 'test'
      projects: '**/*UnitTest*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Create Web App Package (.zip)
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
  
  - task: SonarCloudAnalyze@3
    displayName: 'Run Code Analysis'

  - task: SonarCloudPublish@3
    displayName: 'Publish Quality Gate Result'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact (WebApp.zip)'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

- job: Database
  displayName: 'BUild Database'
  pool:
    vmImage: 'windows-2019'
  
  steps:
  - task: MSBuild@1
    displayName: 'Build Solution WebApp.Database.sqlproj'
    inputs:
      solution: WebApp.Database/WebApp.Database.sqlproj
      msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

